name: CI (Conda/PyTest)
on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    paths-ignore:
      - 'README.md'
jobs:
  build:
    name: Test (${{ matrix.os }}, ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-latest']  #, 'macos-latest']
        python-version: ['3.11']
    steps:
    - uses: actions/checkout@v2
    - uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: 'latest'
        environment-name: 'bakta'
        environment-file: 'environment.yml'
        create-args: python=${{ matrix.python-version }}
        condarc: |
          channels:
            - conda-forge
            - bioconda
        init-shell: bash
        cache-environment: true
        cache-downloads: true
        post-cleanup: 'all'
    - name: Install PyTest
      run: micromamba install pytest pytest-dependency
      shell: bash -l {0}
    - name: Mamba info
      run: |
        micromamba info
        micromamba list
        printenv | sort
      shell: bash -l {0}
    - name: Run PyTest
      if: ${{ matrix.os == 'ubuntu-latest'  ||  matrix.python-version == '3.10'}}
      run: pytest
      shell: bash -l {0}
